# Generated by Django 5.2.4 on 2026-03-12 18:16

import django.db.models.deletion
import shortuuid
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


# FIX: Existing records ko token dene ka function
def set_invite_tokens(apps, schema_editor):
    ChatGroup = apps.get_model('a_rtchat', 'ChatGroup')
    for group in ChatGroup.objects.all():
        group.invite_token = shortuuid.uuid()
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0006_chatgroup_admin_chatgroup_groupchat_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # FIX: Pehle unique=False se field add karo
        migrations.AddField(
            model_name='chatgroup',
            name='invite_token',
            field=models.CharField(blank=True, max_length=50, default=''),
        ),
        # FIX: Existing records ko token do
        migrations.RunPython(set_invite_tokens, migrations.RunPython.noop),
        # FIX: Ab unique=True karo
        migrations.AlterField(
            model_name='chatgroup',
            name='invite_token',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='GroupJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='a_rtchat.chatgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('group', 'user')},
            },
        ),
    ]